[webservers]
wm-1   ansible_host=10.0.1.27 fqdn=fhm2qvk1i852su6ho514.auto.internal
wm-2   ansible_host=10.0.1.35 fqdn=fhm4b56kapi57lsnf1ch.auto.internal

[databases]
main   ansible_host=10.0.1.20 fqdn=fhmppttg8k66q43cccks.auto.internal
replica   ansible_host=10.0.1.21 fqdn=fhmdveg8vcl74novojiv.auto.internal

[storage]
storage   ansible_host=10.0.1.19 fqdn=fhm44la99847g6etdk7u.auto.internal
